import { test, expect } from "@playwright/test";

test("real question bank: import, metadata routes, undo, resume, drafts and folder deletion", async ({ page }) => {
  test.setTimeout(180000);
  const errors:string[]=[];
  page.on("pageerror",e=>errors.push(e.message));
  await page.goto("/");
  await page.getByRole("button",{name:"Create an account",exact:true}).click();
  await page.getByLabel("Username",{exact:true}).fill(`bank${Date.now().toString(36)}`);
  await page.getByLabel("Password",{exact:true}).fill("TestKnowledge2026!");
  await page.getByRole("button",{name:"Create account",exact:true}).click();
  await expect(page.getByRole("heading",{name:"My library."})).toBeVisible();
  await page.getByRole("link",{name:"Mock interview",exact:true}).click();
  await page.getByRole("button",{name:"Import question bank",exact:true}).click();
  const modal=page.getByRole("dialog");
  await expect(modal).toContainText("368 questions");
  const imported=page.waitForResponse(r=>r.url().endsWith("/interview/seed/import") && r.request().method()==="POST");
  await modal.getByRole("button",{name:"Import selected subjects"}).click();
  const importResponse=await imported;
  expect(importResponse.ok()).toBeTruthy();
  expect((await importResponse.json()).created).toBe(368);
  await expect(modal).not.toBeVisible();
  await page.getByLabel("Interview profile",{exact:true}).selectOption("go_core");
  await page.getByLabel("Interview level",{exact:true}).selectOption("3");
  await page.getByRole("checkbox",{name:/Bank testing mode/}).check();
  await page.locator(".interview-source").filter({hasText:"Interview / Go"}).getByRole("checkbox").check();
  const started=page.waitForResponse(r=>r.url().includes("/interview-graph") && r.request().method()==="POST");
  await page.getByRole("button",{name:"Start interview",exact:true}).click();
  const first=await (await started).json();
  expect(first.current.interview_graph.review_credit).toBe(false);
  expect(first.current.progress_version).toBe(0);
  expect(first.graph.state.config.profile).toBe("go_core");
  await expect(page.locator(".interview-question")).toBeVisible();
  await expect(page.locator("textarea")).toHaveCount(0);
  await expect(page.locator(".interview-bank-warning")).toContainText("SRS schedule stays unchanged");
  await page.getByRole("button",{name:"Reveal Answer",exact:true}).click();
  await expect(page.locator(".interview-reference h3")).toHaveText(["Short Answer","Detailed Answer","Source"]);
  await expect(page.locator(".interview-reference .markdown")).toHaveText([".",".","."]);
  await page.screenshot({path:"test-results/interview-bank-desktop.png",fullPage:true});
  async function act(label:string,action:string) {
    const request=page.waitForRequest(r=>r.url().endsWith("/actions") && r.method()==="POST");
    const response=page.waitForResponse(r=>r.url().endsWith("/actions") && r.request().method()==="POST");
    await page.getByRole("button",{name:label,exact:true}).click();
    const body=(await request).postDataJSON();
    expect(body.action).toBe(action);expect(body).not.toHaveProperty("answer_text");expect(body).not.toHaveProperty("answer_language");
    const result=await response;expect(result.ok()).toBeTruthy();return (await result.json()).session;
  }
  let view=await act("Correct","correct");
  expect(view.current.material_id).not.toBe(first.current.material_id);
  expect(view.graph.selection.detected_concepts.every((c:{source:string})=>["answer","hook"].includes(c.source))).toBeTruthy();
  view=await act("Wrong","wrong");
  const beforeSwitch=view;
  view=await act("Next Route","next_route");
  expect(view.summary.correct).toBe(beforeSwitch.summary.correct);
  expect(view.summary.wrong).toBe(beforeSwitch.summary.wrong);
  const undo=page.waitForResponse(r=>r.url().endsWith("/undo"));
  await page.getByRole("button",{name:/Undo last action/}).click();
  view=await (await undo).json();
  expect(view.current.material_id).toBe(beforeSwitch.current.material_id);
  expect(view.graph.state.asked_material_ids).toEqual(beforeSwitch.graph.state.asked_material_ids);
  const question=await page.locator(".interview-question").innerText();
  await page.reload();
  await expect(page.locator(".interview-question")).toHaveText(question);
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole("button",{name:"Correct",exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
  await page.screenshot({path:"test-results/interview-bank-mobile.png",fullPage:true});
  await page.getByRole("button",{name:"End interview",exact:true}).click();
  await expect(page.getByRole("heading",{name:"A little more prepared."})).toBeVisible();
  await page.setViewportSize({width:1440,height:1000});
  await page.locator(".interview-run-top").getByRole("link",{name:"Library"}).click();
  await page.getByRole("link",{name:"Interview / Go",exact:true}).click();
  const deletion=page.waitForResponse(r=>r.request().method()==="DELETE" && r.url().includes("/folders/"));
  await page.getByRole("button",{name:"Delete folder",exact:true}).click();
  await expect(modal).toContainText("130 materials");
  await modal.getByRole("button",{name:"Delete folder",exact:true}).click();
  expect((await deletion).status()).toBe(204);
  await expect(page.getByRole("heading",{name:"My library."})).toBeVisible();
  await expect(page.getByRole("link",{name:"Interview / Go",exact:true})).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("link",{name:"Interview / Go",exact:true})).toHaveCount(0);
  expect(errors).toEqual([]);
});
